dependencies:
  - python=3
  - pip:	
	- altgraph           
    - asn1crypto         
    - astroid            
    - attrs              
    - Automat            
    - beautifulsoup4     
    - bleach             
    - bs4                
    - certifi            
    - cffi               
    - chardet            
    - colorama           
    - constantly         
    - cryptography       
    - cssselect          
    - cycler             
    - decorator          
    - entrypoints        
    - future             
    - html5lib           
    - hyperlink          
    - idna               
    - incremental        
    - ipykernel          
    - ipython            
    - ipython-genutils   
    - isort              
    - jedi               
    - Jinja2             
    - jsonschema         
    - jupyter-client     
    - jupyter-core       
    - jupyterlab         
    - jupyterlab-launcher
    - kiwisolver         
    - lazy-object-proxy  
    - lxml               
    - macholib           
    - MarkupSafe         
    - matplotlib         
    - mccabe             
    - mistune            
    - nbconvert          
    - nbformat           
    - netaddr            
    - notebook           
    - ntlm-auth          
    - numpy              
    - pandas             
    - pandocfilters      
    - parsel             
    - parso              
    - pefile             
    - pickleshare        
    - pip                
    - prompt-toolkit     
    - psutil             
    - px-proxy           
    - pyasn1             
    - pyasn1-modules     
    - pycparser          
    - PyDispatcher       
    - Pygments           
    - PyInstaller        
    - pylint             
    - pyOpenSSL          
    - pyparsing          
    - pypiwin32          
    - python-dateutil    
    - pytz               
    - pywin32            
    - pywinpty           
    - pyzmq              
    - queuelib           
    - requests           
    - requests-ntlm      
    - scapy              
    - scipy              
    - Scrapy             
    - selenium           
    - Send2Trash         
    - service-identity   
    - setuptools         
    - simplegeneric      
    - six                
    - terminado          
    - testpath           
    - tornado            
    - traitlets          
    - Twisted            
    - unicodecsv         
    - urllib3            
    - w3lib              
    - wcwidth            
    - webencodings       
    - winkerberos        
    - wrapt              
    - zope.interface     
