dependencies:
  - python=3
  - pip:
    - backcall
    - bleach
    - colorama
    - cycler
    - decorator
    - defusedxml
    - entrypoints
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - Jinja2
    - jsonschema
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - jupyterlab
    - jupyterlab-server
    - kiwisolver
    - MarkupSafe
    - matplotlib
    - mistune
    - nbconvert
    - nbformat
    - notebook
    - numpy
    - pandas
    - pandocfilters
    - parso
    - pickleshare
    - pip
    - prometheus-client
    - prompt-toolkit
    - Pygments
    - pyparsing
    - python-dateutil
    - pytz
    - pywinpty
    - pyzmq
    - qtconsole
    - scapy
    - scipy
    - selenium
    - Send2Trash
    - setuptools
    - six
    - terminado
    - testpath
    - tornado
    - traitlets
    - urllib3
    - wcwidth
    - webencodings
    - widgetsnbextension
